In [15]:
import pandas as pd

crime_df = pd.read_excel(r'data_files\brottstatistik_bromma_hägersten-älvsjö.xlsx')

crime_df.head(25)

,Anmälda brott,Unnamed: 1,Brottsförebyggande rådet,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025,2026 prel.,2026 prel.,2026 prel.
2,NaN,Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec,Jan,Feb,Mar
3,NaN,Antal,Antal,Antal,Antal,Antal,Antal,Antal,Antal,Antal,Antal,Antal,Antal,Antal,Antal,Antal
4,Stadsdelsområde Bromma (Sthlm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Totalt antal brott,924,784,1001,867,942,903,802,909,948,1145,949,815,772,614,809
6,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3 kap. Brott mot liv och hälsa,43,29,43,54,59,48,51,42,42,49,50,44,46,27,38
8,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,4 kap. Brott mot frihet och frid,97,77,92,106,138,80,97,109,91,91,82,80,91,75,86
10,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5 kap. Ärekränkningsbrott,4,3,9,5,4,9,18,4,2,1,2,4,6,3,5
12,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6 kap. Sexualbrott,13,3,15,6,33,28,13,32,26,15,15,11,11,21,11
14,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,7 kap. Brott mot familj,1,1,1,0,2,0,0,0,0,1,0,1,2,0,0
16,8-12 kap. Brott mot förmögenhet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"8 kap. Stöld, rån m.m.",237,174,233,210,232,232,203,219,223,248,180,162,133,128,187
18,8-12 kap. Brott mot förmögenhet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,"8 kap. Stöld, rån m.m.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,därav biltillgrepp,5,4,8,5,8,2,4,2,1,1,0,2,2,1,4
21,8-12 kap. Brott mot förmögenhet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,"8 kap. Stöld, rån m.m.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,därav inbrottsstöld i bostad,18,10,13,7,8,15,7,14,24,5,15,29,23,7,7
24,8-12 kap. Brott mot förmögenhet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

crime_bromma_df = pd.read_excel(r'data_files\brottstatistik_bromma_hägersten-älvsjö.xlsx')
crime_bromma_df = crime_bromma_df.iloc[[5, 7, 9, 11, 13, 15, 17, 20, 23, 26, 28, 30, 32, 33, 34]]
crime_bromma_df.columns = ['Anmälda brott', 'Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']

crime_bromma_df

,Anmälda brott,Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec,Jan,Feb,Mar
5,Totalt antal brott,924,784,1001,867,942,903,802,909,948,1145,949,815,772,614,809
7,3 kap. Brott mot liv och hälsa,43,29,43,54,59,48,51,42,42,49,50,44,46,27,38
9,4 kap. Brott mot frihet och frid,97,77,92,106,138,80,97,109,91,91,82,80,91,75,86
11,5 kap. Ärekränkningsbrott,4,3,9,5,4,9,18,4,2,1,2,4,6,3,5
13,6 kap. Sexualbrott,13,3,15,6,33,28,13,32,26,15,15,11,11,21,11
15,7 kap. Brott mot familj,1,1,1,0,2,0,0,0,0,1,0,1,2,0,0
17,"8 kap. Stöld, rån m.m.",237,174,233,210,232,232,203,219,223,248,180,162,133,128,187
20,därav biltillgrepp,5,4,8,5,8,2,4,2,1,1,0,2,2,1,4
23,därav inbrottsstöld i bostad,18,10,13,7,8,15,7,14,24,5,15,29,23,7,7
26,"därav rån, inkl. grovt",1,4,1,0,4,2,3,1,1,1,1,0,3,0,1
28,9 kap. Bedrägeri och annan oredlighet,143,125,132,93,71,123,85,116,119,121,84,157,93,110,136
30,12 kap. Skadegörelsebrott,264,247,291,244,222,253,242,253,254,462,321,236,235,148,218
32,13 kap. Allmänfarliga brott,1,0,0,2,2,2,3,2,2,3,1,0,2,0,0
33,Brott mot narkotikastrafflagen,30,35,80,75,57,36,30,39,62,49,71,47,53,28,35
34,Vapenlagen,5,1,3,5,6,6,2,7,2,5,6,1,6,2,2

In [41]:
import pandas as pd

crime_hägersten_älvsjö_df = pd.read_excel(r'data_files\brottstatistik_bromma_hägersten-älvsjö.xlsx')
crime_hägersten_älvsjö_df = crime_hägersten_älvsjö_df.iloc[[36, 38, 40, 42, 44, 46, 48, 51, 54, 57, 59, 61, 63, 64, 65]]
crime_hägersten_älvsjö_df.columns = ['Anmälda brott', 'Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']
crime_hägersten_älvsjö_df['Stadsdel'] = 'Hägersten-Älvsjö'

crime_hägersten_älvsjö_df

,Anmälda brott,Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec,Jan,Feb,Mar,Stadsdel
36,Totalt antal brott,1311,1253,1495,1524,1820,1508,1592,1847,2220,2061,1674,1500,1413,1286,1656,Hägersten-Älvsjö
38,3 kap. Brott mot liv och hälsa,90,64,110,71,103,91,77,86,90,84,91,106,86,80,87,Hägersten-Älvsjö
40,4 kap. Brott mot frihet och frid,166,130,180,142,177,171,116,152,207,157,160,183,132,124,169,Hägersten-Älvsjö
42,5 kap. Ärekränkningsbrott,9,5,11,8,13,9,12,7,7,7,7,7,12,6,8,Hägersten-Älvsjö
44,6 kap. Sexualbrott,17,22,15,22,121,13,28,23,34,19,33,12,16,35,27,Hägersten-Älvsjö
46,7 kap. Brott mot familj,2,1,0,1,2,1,1,1,1,0,0,1,1,0,3,Hägersten-Älvsjö
48,"8 kap. Stöld, rån m.m.",251,223,310,300,336,311,325,391,404,382,312,294,260,242,282,Hägersten-Älvsjö
51,därav biltillgrepp,6,11,2,1,6,4,4,6,8,7,7,2,1,3,6,Hägersten-Älvsjö
54,därav inbrottsstöld i bostad,10,4,7,4,6,6,10,9,13,10,9,9,6,6,6,Hägersten-Älvsjö
57,"därav rån, inkl. grovt",7,5,7,5,5,4,4,7,3,1,2,5,12,4,1,Hägersten-Älvsjö
59,9 kap. Bedrägeri och annan oredlighet,176,232,207,229,301,184,238,203,200,165,162,149,175,168,181,Hägersten-Älvsjö
61,12 kap. Skadegörelsebrott,397,334,428,474,481,510,572,761,1036,994,697,520,500,427,587,Hägersten-Älvsjö
63,13 kap. Allmänfarliga brott,5,6,2,5,2,5,4,2,5,4,2,7,2,5,4,Hägersten-Älvsjö
64,Brott mot narkotikastrafflagen,70,84,78,127,134,86,91,92,105,85,70,97,74,62,151,Hägersten-Älvsjö
65,Vapenlagen,8,5,13,4,5,4,9,6,4,6,5,8,12,9,14,Hägersten-Älvsjö

In [ ]:
import pandas as pd

crime_merged_df = pd.concat([crime_bromma_df, crime_hägersten_älvsjö_df], axis=0)

crime_merged_df['Anmälda brott'].str.strip()

crime_merged_df.replace({
    '3 kap. Brott mot liv och hälsa': 'Brott mot liv och hälsa',
    '4 kap. Brott mot frihet och frid': 'Brott mot frihet och frid',
    '5 kap. Ärekränkningsbrott': 'Ärekränkningsbrott',
    '6 kap. Sexualbrott': 'Sexualbrott',
    '7 kap. Brott mot familj': 'Brott mot familj',
    '8 kap. Stöld, rån m.m.': 'Stöld, rån m.m.',
    'därav biltillgrepp': 'Bilstöld',
    'därav inbrottsstöld i bostad': 'Inbrottsstöld i bostad',
    'därav rån, inkl. grovt': 'Rån',
    '9 kap. Bedrägeri och annan oredlighet': 'Bedrägeri och annan oredlighet',
    '12 kap. Skadegörelsebrott': 'Skadegörelsebrott',
    '13 kap. Allmänfarliga brott': 'Allmänfarliga brott'


}, inplace=True)

crime_merged_df

C:\Users\kalle\AppData\Local\Temp\ipykernel_15004\2620324450.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  crime_merged_df.replace({

,Anmälda brott,Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec,Jan,Feb,Mar,Stadsdel
5,Totalt antal brott,924,784,1001,867,942,903,802,909,948,1145,949,815,772,614,809,Bromma
7,Brott mot liv och hälsa,43,29,43,54,59,48,51,42,42,49,50,44,46,27,38,Bromma
9,Brott mot frihet och frid,97,77,92,106,138,80,97,109,91,91,82,80,91,75,86,Bromma
11,Ärekränkningsbrott,4,3,9,5,4,9,18,4,2,1,2,4,6,3,5,Bromma
13,Sexualbrott,13,3,15,6,33,28,13,32,26,15,15,11,11,21,11,Bromma
15,Brott mot familj,1,1,1,0,2,0,0,0,0,1,0,1,2,0,0,Bromma
17,"Stöld, rån m.m.",237,174,233,210,232,232,203,219,223,248,180,162,133,128,187,Bromma
20,Bilstöld,5,4,8,5,8,2,4,2,1,1,0,2,2,1,4,Bromma
23,Inbrottsstöld i bostad,18,10,13,7,8,15,7,14,24,5,15,29,23,7,7,Bromma
26,Rån,1,4,1,0,4,2,3,1,1,1,1,0,3,0,1,Bromma
28,Bedrägeri och annan oredlighet,143,125,132,93,71,123,85,116,119,121,84,157,93,110,136,Bromma
30,Skadegörelsebrott,264,247,291,244,222,253,242,253,254,462,321,236,235,148,218,Bromma
32,Allmänfarliga brott,1,0,0,2,2,2,3,2,2,3,1,0,2,0,0,Bromma
33,Brott mot narkotikastrafflagen,30,35,80,75,57,36,30,39,62,49,71,47,53,28,35,Bromma
34,Vapenlagen,5,1,3,5,6,6,2,7,2,5,6,1,6,2,2,Bromma
36,Totalt antal brott,1311,1253,1495,1524,1820,1508,1592,1847,2220,2061,1674,1500,1413,1286,1656,Hägersten-Älvsjö
38,Brott mot liv och hälsa,90,64,110,71,103,91,77,86,90,84,91,106,86,80,87,Hägersten-Älvsjö
40,Brott mot frihet och frid,166,130,180,142,177,171,116,152,207,157,160,183,132,124,169,Hägersten-Älvsjö
42,Ärekränkningsbrott,9,5,11,8,13,9,12,7,7,7,7,7,12,6,8,Hägersten-Älvsjö
44,Sexualbrott,17,22,15,22,121,13,28,23,34,19,33,12,16,35,27,Hägersten-Älvsjö
46,Brott mot familj,2,1,0,1,2,1,1,1,1,0,0,1,1,0,3,Hägersten-Älvsjö
48,"Stöld, rån m.m.",251,223,310,300,336,311,325,391,404,382,312,294,260,242,282,Hägersten-Älvsjö
51,Bilstöld,6,11,2,1,6,4,4,6,8,7,7,2,1,3,6,Hägersten-Älvsjö
54,Inbrottsstöld i bostad,10,4,7,4,6,6,10,9,13,10,9,9,6,6,6,Hägersten-Älvsjö
57,Rån,7,5,7,5,5,4,4,7,3,1,2,5,12,4,1,Hägersten-Älvsjö
59,Bedrägeri och annan oredlighet,176,232,207,229,301,184,238,203,200,165,162,149,175,168,181,Hägersten-Älvsjö
61,Skadegörelsebrott,397,334,428,474,481,510,572,761,1036,994,697,520,500,427,587,Hägersten-Älvsjö
63,Allmänfarliga brott,5,6,2,5,2,5,4,2,5,4,2,7,2,5,4,Hägersten-Älvsjö
64,Brott mot narkotikastrafflagen,70,84,78,127,134,86,91,92,105,85,70,97,74,62,151,Hägersten-Älvsjö
65,Vapenlagen,8,5,13,4,5,4,9,6,4,6,5,8,12,9,14,Hägersten-Älvsjö