In [1]:
import pandas as pd

population_df = pd.read_excel(r'data\1.2-folkmangd-den-31-dec-2010-2034.xlsx')
population_df = population_df.dropna(how='all')
population_df = population_df.dropna(axis=1, how='all')
population_df = population_df.iloc[3:17]
population_df = population_df.iloc[:, [0, 4]]
population_df.columns = ['area', 'population_2024']
population_df['population_2024'] = population_df['population_2024'].round(0).astype(int)

population_df

                    area  population_2024
3              Västerort           254678
4                  Järva            95220
5     Hässelby-Vällingby            76340
6                 Bromma            83118
8            Inre staden           356620
9            Kungsholmen            70932
10     Norra innerstaden           155286
11             Södermalm           130402
13              Söderort           380639
14  Enskede-Årsta-Vantör           105241
15             Skarpnäck            46407
16                Farsta            62085
17      Hägersten-Älvsjö           128794
18            Skärholmen            38112

In [2]:
import pandas as pd

crime_df = pd.read_excel(r'data\1.63-anmalda-brott-2024.xlsx')
crime_df = crime_df.dropna(how='all')
crime_df = crime_df.dropna(axis=1, how='all')
crime_df = crime_df.iloc[5:19]
crime_df = crime_df.iloc[:, [0, 6]]
crime_df.columns = ['area', 'reported_crime_per_1000_2024']
crime_df['reported_crime_per_1000_2024'] = pd.to_numeric(crime_df['reported_crime_per_1000_2024'])
crime_df['reported_crime_per_1000_2024'] = crime_df['reported_crime_per_1000_2024'].round(0).astype(int)
crime_df

                    area  reported_crime_per_1000_2024
5              Västerort                           180
6                  Järva                           168
7     Hässelby-Vällingby                           209
8                 Bromma                           167
10           Inre staden                           238
11           Kungsholmen                           169
12     Norra innerstaden                           273
13             Södermalm                           235
15              Söderort                           177
16  Enskede-Årsta-Vantör                           204
17             Skarpnäck                           166
18                Farsta                           195
19      Hägersten-Älvsjö                           154
20            Skärholmen                           167

In [4]:
merged_table = pd.merge(population_df, crime_df, on='area')

merged_table

                    area  population_2024  reported_crime_per_1000_2024
0              Västerort           254678                           180
1                  Järva            95220                           168
2     Hässelby-Vällingby            76340                           209
3                 Bromma            83118                           167
4            Inre staden           356620                           238
5            Kungsholmen            70932                           169
6      Norra innerstaden           155286                           273
7              Södermalm           130402                           235
8               Söderort           380639                           177
9   Enskede-Årsta-Vantör           105241                           204
10             Skarpnäck            46407                           166
11                Farsta            62085                           195
12      Hägersten-Älvsjö           128794                           154
13            Skärholmen            38112                           167