# EDA - Brottsstatistik

## Initial EDA

In [328]:
import pandas as pd
import duckdb
import matplotlib

df_raw = pd.read_excel('../data_files/brå_2021_2025_raw.xls', header=None)

df_raw.head(10)

,0,1,2,3,4,5,6,7,8,9,10
0,Anmälda brott,NaN,Brottsförebyggande rådet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2021,2021,2022,2022,2023,2023,2024,2024,2025,2025
3,NaN,Helår,Helår,Helår,Helår,Helår,Helår,Helår,Helår,Helår,Helår
4,NaN,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv
5,Stadsdelsområde Bromma (Sthlm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3 kap. Brott mot liv och hälsa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,därav misshandel inkl. grov,472,581,458,558,506,615,511,617,501,603
9,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [329]:
df_raw.shape

(139, 11)

In [330]:
df_raw.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [331]:
df_raw.iloc[2:5, :10]

,0,1,2,3,4,5,6,7,8,9
2,NaN,2021,2021,2022,2022,2023,2023,2024,2024,2025
3,NaN,Helår,Helår,Helår,Helår,Helår,Helår,Helår,Helår,Helår
4,NaN,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal,/100 000 inv,Antal

In [332]:
# Se alla brottstyper som innehåller data (not null)
# Kolumn 0 = Brottstyper

list(df_raw[0].dropna().unique())

['Anmälda brott',
 'Stadsdelsområde Bromma (Sthlm)',
 '3-7 kap. Brott mot person',
 '3 kap. Brott mot liv och hälsa',
 'därav misshandel inkl. grov',
 '4 kap. Brott mot frihet och frid',
 '5 kap. Ärekränkningsbrott',
 '6 kap. Sexualbrott',
 '7 kap. Brott mot familj',
 '8-12 kap. Brott mot förmögenhet',
 '8 kap. Stöld, rån m.m.',
 'därav biltillgrepp',
 'därav cykeltillgrepp',
 'därav stöld ur och från motordrivet fordon',
 'därav inbrottsstöld i bostad',
 'därav stöld och snatteri i butik, varuhus o.d.',
 'därav fickstöld',
 'därav rån, inkl. grovt',
 '9 kap. Bedrägeri och annan oredlighet',
 '10 kap. Förskingring och annan trolöshet',
 '11 kap. Brott mot borgenärer m.m.',
 '12 kap. Skadegörelsebrott',
 '13-15 kap. Brott mot allmänheten',
 '13 kap. Allmänfarliga brott',
 '14 kap. Förfalskningsbrott',
 '15 kap. Mened, falskt åtal m.m.',
 '16-20 kap. Brott mot staten',
 '16 kap. Brott mot allmän ordning',
 '17 kap. Brott mot allmän verksamhet',
 '18-20 kap. Högmålsbrott, brott mot rikets säkerhet, tjänstefel m.m.',
 'Brott mot trafikbrottslagen',
 'Brott mot narkotikastrafflagen',
 'Brott mot miljöbalken',
 'Brott mot skattebrottslagen m.m.',
 'Brott mot bidragsbrottslagen',
 'Lag om straff för smuggling',
 'Alkohollagen',
 'Vapenlagen',
 'Övriga specialstraffrättsliga författningar',
 'Stadsdelsområde Hägersten-Älvsjö (Sthlm)',
 'Det föreligger ett visst bortfall av skattebrott i statistiken 2023 och 2024. Jämförelser bör därför inte göras med de åren.',
 'Smugglingsbrott - Från och med september 2023 samlar Brå in data från Tullverket med en ny metod som innebär mer komplett information om anmälda brott och brottsmisstankar jämfört med tidigare. Statistiken över anmälda smugglingsbrott innan och efter 2023 är således inte jämförbar.',
 'I juni 2016 har redovisningen av folkmängd ändrats. Numera beräknas folkmängden efter folkbokföringsadress, tidigare utgick beräkningen efter folkbokföringsförsamling. Uppdatering har även skett bakåt i tiden (från och med 2002). Samtliga aktuella stadsområden i Stockholms kommun berörs (Bromma, Enskede-Årsta-Vantör, Farsta, Hägersten-Liljeholmen, Hässelby-Vällingby, Kungsholmen, Norrmalm, Rinkeby-Kista, Skarpnäck, Skärholmen, Spånga-Tensta, Södermalm, Älvsjö, Östermalm). Beräkningen av folkmängd efter folkbokföringsförsamling är något högre än  beräkningen efter folkbokföringsadress. Uppdateringen innebär att antalet redovisade brott per 100 000 invånare blivit fler under perioden 2002-2016 än vad som tidigare redovisats. I och med ändringen redovisas folkmängden för stadsområdena i kommunerna Stockholm, Göteborg och Malmö med samma metod.',
 'Stadsdelen bildades 2021-01-01, statistik innan detta datum är framtagen i efterhand för att möjliggöra jämförelser bakåt i tiden.']

### Kommentar:
Lite konstig struktur på filen..

* Rad 0-4: Headers/metadata
* Totalt antal brott: kolumn 1, 3, 5..
* Brott per capita: kolumn 2, 4, 6..

## Cleaning ##

Förbered tabellen för att enklare kunna filtrera och sedan rensa datan

#### Behåll endast brottsdata per capita

In [ ]:
# Skapa ny df med de rader vi vill behålla
# Kolumn 0 = brottstyp
# Kolumn 2,4,6.. = brott per capita

per_capita_cols = [0] + list(range(2,25,2))

df_cleaned = df_raw.iloc[:, per_capita_cols].copy()

df_cleaned.head(10)ß

IndexError: positional indexers are out-of-bounds

#### Lägg till datumintervall

* kvartal och år

#### Ge kolumnerna namn

In [ ]:
df_cleaned

In [223]:
df_cleaned.columns = ['brottstyp'] + quarters

#### Lägg till radnummer

In [224]:
# För att vi ska kunna filtrera på område

df_cleaned['radnr'] = range(len(df_cleaned))

df_cleaned.head(10)

,brottstyp,2023_Kvartal 1,2023_Kvartal 2,2023_Kvartal 3,2023_Kvartal 4,2024_Kvartal 1,2024_Kvartal 2,2024_Kvartal 3,2024_Kvartal 4,2025_Kvartal 1,2025_Kvartal 2,2025_Kvartal 3,2025_Kvartal 4,radnr
0,Anmälda brott,Brottsförebyggande rådet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,NaN,2023,2023,2023,2023,2024,2024,2024,2024,2025,2025,2025,2025,2
3,NaN,Kvartal 1,Kvartal 2,Kvartal 3,Kvartal 4,Kvartal 1,Kvartal 2,Kvartal 3,Kvartal 4,Kvartal 1,Kvartal 2,Kvartal 3,Kvartal 4,3
4,NaN,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,/100 000 inv,4
5,Stadsdelsområde Bromma (Sthlm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
6,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
7,3 kap. Brott mot liv och hälsa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
8,därav misshandel inkl. grov,147,187,163,118,145,182,138,152,129,170,142,162,8
9,3-7 kap. Brott mot person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9

#### Lägg till kolumn för område

In [225]:
# Hitta vilka rader som gälller för Bromma

df_cleaned[df_cleaned['brottstyp'].str.contains('Bromma|Årsta')] # ändra till älvsjö

,brottstyp,2023_Kvartal 1,2023_Kvartal 2,2023_Kvartal 3,2023_Kvartal 4,2024_Kvartal 1,2024_Kvartal 2,2024_Kvartal 3,2024_Kvartal 4,2025_Kvartal 1,2025_Kvartal 2,2025_Kvartal 3,2025_Kvartal 4,radnr
5,Stadsdelsområde Bromma (Sthlm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
67,Stadsdelsområde Enskede - Årsta - Vantör (Sthlm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67
135,Stadsdelsområde Bromma (Sthlm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135
136,I juni 2016 har redovisningen av folkmängd änd...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136
137,Stadsdelsområde Enskede - Årsta - Vantör (Sthlm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137
138,I juni 2016 har redovisningen av folkmängd änd...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138

In [ ]:
# Lägg till kolumn med områdesnamn

BROMMA_START = 5
ENSKEDE_START = 67

df_cleaned = duckdb.sql(f"""--sql
SELECT 
    *,
    CASE 
        WHEN radnr >= {BROMMA_START} AND radnr < {ENSKEDE_START} THEN 'Bromma'
        WHEN radnr >= {ENSKEDE_START} THEN 'Enskede-Årsta-Vantör'
    END AS område
FROM df_cleaned
""").df()

df_cleaned()

TypeError: 'DataFrame' object is not callable

### Filtrering ###

Filtrering av relevanta brott med duckdb
1. Vi väljer de brottstyper vi vill ha som är relevnta för projektet
2. Översätter namnen så att de är lättare att förstå

#### 1. Brottstyper som är relevnta för projektet

In [ ]:
df_cleaned = duckdb.sql("""---sql
SELECT * 
FROM df_cleaned
WHERE brottstyp IN (
    'därav misshandel inkl. grov',
    '4 kap. Brott mot frihet och frid',
    '6 kap. Sexualbrott',
    'därav biltillgrepp',
    'därav cykeltillgrepp',
    'därav stöld ur och från motordrivet fordon',
    'därav inbrottsstöld i bostad',
    'därav rån, inkl. grovt',
    '12 kap. Skadegörelsebrott',
    'Brott mot narkotikastrafflagen'      
)
""").df()

df_cleaned

,brottstyp,2023_Kvartal 1,2023_Kvartal 2,2023_Kvartal 3,2023_Kvartal 4,2024_Kvartal 1,2024_Kvartal 2,2024_Kvartal 3,2024_Kvartal 4,2025_Kvartal 1,2025_Kvartal 2,2025_Kvartal 3,2025_Kvartal 4,radnr
0,därav misshandel inkl. grov,147,187,163,118,145,182,138,152,129,170,142,162,8
1,4 kap. Brott mot frihet och frid,277,322,295,324,284,377,383,353,320,390,357,304,10
2,6 kap. Sexualbrott,45,73,63,49,62,86,56,41,37,81,85,49,14
3,därav biltillgrepp,21,18,17,36,18,12,14,13,20,18,8,4,19
4,därav cykeltillgrepp,83,193,214,117,80,202,262,132,78,220,201,101,22
5,därav stöld ur och från motordrivet fordon,123,141,109,118,58,85,91,85,97,72,97,76,25
6,därav inbrottsstöld i bostad,33,24,28,32,25,53,70,57,49,36,54,59,28
7,"därav rån, inkl. grovt",13,17,19,6,11,10,10,7,7,7,6,2,37
8,12 kap. Skadegörelsebrott,1420,1827,1880,2430,1720,1906,1499,1754,965,865,901,1226,45
9,Brott mot narkotikastrafflagen,124,174,135,189,146,181,128,207,174,202,158,201,59
10,därav misshandel inkl. grov,246,265,246,211,212,293,252,262,236,284,251,262,70
11,4 kap. Brott mot frihet och frid,264,341,374,430,426,501,424,420,391,435,416,437,72
12,6 kap. Sexualbrott,56,46,58,56,88,67,61,56,46,53,58,61,76
13,därav biltillgrepp,11,17,24,21,18,14,21,23,28,10,14,10,81
14,därav cykeltillgrepp,59,145,159,86,57,151,178,90,53,143,148,67,84
15,därav stöld ur och från motordrivet fordon,105,130,117,148,79,64,120,104,86,57,96,62,87
16,därav inbrottsstöld i bostad,18,31,22,27,28,32,29,26,48,15,13,29,90
17,"därav rån, inkl. grovt",34,19,27,17,16,21,24,8,10,10,12,10,99
18,12 kap. Skadegörelsebrott,2095,2845,3933,3013,2660,2181,2001,2316,1583,2064,2167,2576,107
19,Brott mot narkotikastrafflagen,349,407,321,397,429,366,295,251,338,308,356,324,121

#### 2. Översätt namnen

In [ ]:
df_cleaned = duckdb.sql("""--sql
SELECT
    CASE brottstyp
        WHEN 'därav misshandel inkl. grov' THEN 'Misshandel'
        WHEN '4 kap. Brott mot frihet och frid' THEN 'Hot & olaga intrång'
        WHEN '6 kap. Sexualbrott' THEN 'Sexualbrott'
        WHEN 'därav biltillgrepp' THEN 'Bilstöld'
        WHEN 'därav cykeltillgrepp' THEN 'Cykelstöld'
        WHEN 'därav stöld ur och från motordrivet fordon' THEN 'Stöld från fordon'
        WHEN 'därav inbrottsstöld i bostad' THEN 'Bostadsinbrott'
        WHEN 'därav rån, inkl. grovt' THEN 'Rån'
        WHEN '12 kap. Skadegörelsebrott' THEN 'Skadegörelse'
        WHEN 'Brott mot narkotikastrafflagen' THEN 'Narkotikabrott'
    END AS brottstyp,
    COLUMNS('.*Kvartal.*')                
FROM df_cleaned
WHERE brottstyp IN (
    'därav misshandel inkl. grov',
    '4 kap. Brott mot frihet och frid',
    '6 kap. Sexualbrott',
    'därav biltillgrepp',
    'därav cykeltillgrepp',
    'därav stöld ur och från motordrivet fordon',
    'därav inbrottsstöld i bostad',
    'därav rån, inkl. grovt',
    '12 kap. Skadegörelsebrott',
    'Brott mot narkotikastrafflagen'
)
""").df()

df_cleaned

,brottstyp,2023_Kvartal 1,2023_Kvartal 2,2023_Kvartal 3,2023_Kvartal 4,2024_Kvartal 1,2024_Kvartal 2,2024_Kvartal 3,2024_Kvartal 4,2025_Kvartal 1,2025_Kvartal 2,2025_Kvartal 3,2025_Kvartal 4
0,Misshandel,147,187,163,118,145,182,138,152,129,170,142,162
1,Hot & olaga intrång,277,322,295,324,284,377,383,353,320,390,357,304
2,Sexualbrott,45,73,63,49,62,86,56,41,37,81,85,49
3,Bilstöld,21,18,17,36,18,12,14,13,20,18,8,4
4,Cykelstöld,83,193,214,117,80,202,262,132,78,220,201,101
5,Stöld från fordon,123,141,109,118,58,85,91,85,97,72,97,76
6,Bostadsinbrott,33,24,28,32,25,53,70,57,49,36,54,59
7,Rån,13,17,19,6,11,10,10,7,7,7,6,2
8,Skadegörelse,1420,1827,1880,2430,1720,1906,1499,1754,965,865,901,1226
9,Narkotikabrott,124,174,135,189,146,181,128,207,174,202,158,201